name: cached tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '17 22 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: sblauth/cashocs:latest

    steps:
    - name: Delete current installation in docker image
      shell: bash -l {0}
      run: |
        conda activate cashocs
        pip uninstall -y cashocs
        rm -R /root/cashocs

    - name: Checkout repository
      uses: actions/checkout@v2 

    - name: Install cashocs
      shell: bash -l {0}
      run: |
        conda activate cashocs
        pip install .

    - name: Run tests
      shell: bash -l {0}
      run: |
        conda activate cashocs
        coverage run --source=cashocs -m pytest

    - name: Generate .xml coverage results
      shell: bash -l {0}
      run: |
        conda activate cashocs
        coverage xml

    - name: Upload coverage to codecov.io
      uses: codecov/codecov-action@v1
      with:
        files: coverage.xml
