name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda create -n fenics -c conda-forge fenics=2019 meshio">=4.1.0" pytest">=6.0.0" deprecated">=1.2.10" matplotlib-base python">=3.6" coverage
        conda init bash
    - name: Install cashocs
      shell: bash -l {0}
      run: |
        source $CONDA/bin/activate fenics
        pip3 install .
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        source $CONDA/bin/activate fenics
        pytest
    - name: Generate report
    - run: |
        coverage run --source=cashocs -m pytest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
