name: ci

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '17 22 * * *'

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: sblauth/fast-cashocs:latest

    steps:
    - name: Delete old installation
      shell: bash -l {0}
      run: |
        conda activate cashocs
        pip uninstall -y cashocs
        rm -R /root/cashocs

    - name: Checkout repository
      uses: actions/checkout@v2 

    - name: Update cashocs installation
      shell: bash -l {0}
      run: |
        conda activate cashocs
        pip install .

    - name: Run tests
      shell: bash -l {0}
      run: |
        conda activate cashocs
        pytest
