name: ci

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '17 22 * * *'

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: sblauth/cashocs-test-env:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 

    - name: Install cashocs
      shell: bash -l {0}
      run: |
        conda activate cashocs
        pip install .

    - name: Run tests
      shell: bash -l {0}
      run: |
        conda activate cashocs
        pytest
