name: complete ci

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '17 22 * * *'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda create -n fenics -c conda-forge fenics=2019 meshio">=4.1.0" pytest">=6.0.0" deprecated">=1.2.10" matplotlib-base gmsh">=4.8" python">=3.6" coverage
        conda init bash

    - name: Install package
      shell: bash -l {0}
      run: |
        source $CONDA/bin/activate fenics
        pip install .

    - name: Run tests and generate coverage
      shell: bash -l {0}
      run: |
        source $CONDA/bin/activate fenics
        coverage run --source=cashocs -m pytest

    - name: Generate .xml coverage results
      shell: bash -l {0}
      run: |
        source $CONDA/bin/activate fenics
        coverage xml

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        files: coverage.xml
