name: coverage


on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '37 22 * * *'

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
        conda init bash

    - name: Install mamba
      shell: bash -l {0}
      run: |
        conda install -c conda-forge mamba

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        mamba create --strict-channel-priority -n fenics -c conda-forge fenics=2019 meshio">=5.0.0" pytest">=7.0.0" deprecated">=1.2.12" gmsh">=4.8"  coverage">=6.3" python=3.9

    - name: Install package
      shell: bash -l {0}
      run: |
        source $CONDA/bin/activate fenics
        pip install .

    - name: Run tests and generate coverage
      shell: bash -l {0}
      run: |
        source $CONDA/bin/activate fenics
        coverage run --source=cashocs -m pytest

    - name: Generate .xml coverage results
      shell: bash -l {0}
      run: |
        source $CONDA/bin/activate fenics
        coverage xml

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        files: coverage.xml
