name: dockerbuild

on:
  workflow_dispatch:
  schedule:
    - cron: '13 0 * * *'

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/sblauth/cashocs_testimage:latest

#      - name: Login to GitHub Packages
#        run: docker login -u ${{ github.actor }} -p ${{ secrets.GHCR_PAT }} ghcr.io
#
#      - name: Build Docker image
#        run: docker build -t ghcr.io/sblauth/cashocs_testimage:latest ./docker/
#
#      - name: Push Docker image to GitHub Packages
#        run: docker push ghcr.io/sblauth/cashocs_testimage:latest
#     
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GHCR_PAT }}
          event-type: build_success
